# Generated by Django 2.2.6 on 2019-10-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
