# Generated by Django 2.2.6 on 2019-10-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
