# Generated by Django 2.2.6 on 2019-10-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['-name'], 'verbose_name': 'institution', 'verbose_name_plural': 'institutions'},
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['name'], name='charity_ins_name_34adca_idx'),
        ),
    ]
